### PR TITLE
matUtils update- metadata and vcf writing

### PR DESCRIPTION
**Pull request by jmcbroome**
I've refactored matUtils to move the masking procedure into a dedicated function and added two new primary functions; one, copying in the source code of matToVcf to give it vcf production functionality (credit to Angie for writing something very readable and portable), and two, the calculation and storage of the number of equally parsimonious placements for all leaf nodes. These changes also involved extension of the Protocol Buffer .proto and the addition of minor attributes (including saving/loading of said attributes) to the Node and Tree class definitions and headers to support metadata value storage. I also edited the CMakeLists file to automatically compile matUtils along with the primary package on installation. The new PB format should be backwards and forwards compatible and I've included handling for older file formats where needed.

Two minor open issues- one, I'm not certain that the node mutation path collection code is entirely sensible (though it works just fine, at least in most cases) and it deserves some review; two, for some reason I can't just include the usher_graph.hpp or the compiler insists that mapper2_body isn't defined- including usher_mapper.cpp instead gets around this, but its not ideal.

### CODE REVIEW

**Comment by yatisht** [comment]
Thanks for your detailed summary of the PR. But there needs to be a few changes before I merge:

1. Your PR is undoing the enhancements (using const, at instead of [] for dictionary, warning messages, new member functions like LCA etc.) I have been making for the last several days. When you merge, you want to merge to the *latest* commit and not the one you started from. Please make sure your PR does not override my changes.
2. You should not be including .cpp files. I think the reason you're seeing an error while compiling is because you have not included usher_mapper.cpp in add_executable for matUtils in CMakeLists.txt, hence the compiler does not compile and link the necessary object file. Please try this out.
3. Please update the README with the new usage of matUtils (removing the current description of matToVcf).

I will review the issue of node mutation paths once you update the PR.

**Comment by jmcbroome** [comment]
Your fix for point 2 was perfect, thanks. For point 1, yeah I see what you're talking about. Git was claiming I was up to date but my mutation_annotated_tree class for example clearly did not have the subtree member function. I did try to merge upstream a few days ago, I probably screwed it up when trying to fix merge conflicts and it was marked as deleted on my fork or something. I've done manual review and a bunch of comparison and I believe its now concurrent with your changes over the last few days- at least any changes to the mutation_annotated_tree structures and usher.cpp itself- including the new methods and the shift to using const.

I did accidentally commit some in-progress code I'm applying for a new uncertainty metric when applying these updates (matUtils.cpp lines 171-250).  It's calculating the maximum pairwise distance of the nearest common ancestor of all equally parsimonious placements of a node. I've commented out that in-progress code because I have not debugged it and deleting it makes me nervous with mistakes I've made with Git this week, haha. I'm intending to include the functional version in the next pull request. Feel free to look it over in the meantime if you like- its an odd little algorithmic problem involving extending the common ancestors of an arbitrary number of nodes and traversing paths and summing distances. It's definitely not optimal in runtime at the moment, though- I think I can further filter my common ancestor candidate set before trying to traverse. Or I might be missing some altogether simpler way to do things.

Also, I have not tried to remove the matToVCF executable, though its deprecated now. If you're happy with the reworked and updated matUtils, I can look at taking it out in the next major commit.  For the .README, I've updated the description of matToVcf to talk about matUtils. Going forward, if we do move this to a subdirectory especially, it may be worth dedicating space on the README to explaining how to interpret some of the uncertainty metrics we are developing. 

Let me know if I missed anything else and thank you for your patience! I'm pretty sure I've learned more in the two weeks then I did in the four months preceding, both about C++ and about Git generally.

**Comment by yatisht** [comment]
Excellent. And thanks for addressing my comments so quickly.

Overall, this looks good to me. I will merge this now, but I intend to make a few changes that you should be aware of:

1. I still see mentions of matToVcf in the README, which I'll remove.
2. I will remove building matToVcf in CMakeLists.txt. I think I might even remove matToVcf.cpp entirely if you're doing the same thing in matUtils.
3. I will remove your inline comments marked with 'JMB'. If you want to discuss something you're unsure of, just use GitHub to add comments on those lines and tag me or Angie.
4. We use GitHub Actions (https://github.com/yatisht/usher/actions) to check if everything builds fine on Ubuntu and MacOS. I will add matUtils to it and remove matToVcf.

**Comment by yatisht** [comment]
@jmcbroome Looks like you just addressed my point 1. I'll wait for you to give a thumb up on when to merge.

**Comment by jmcbroome** [comment]
Oh sorry I'd just noticed I'd missed the table of contents link. Hadn't seen your reply yet. Yes, please go ahead with everything else! If you do delete matToVcf altogether I'll remove mention of it from the readme description of matUtils.

**Pull request merged**
