### PR TITLE
Updates to Mask, Uncertainty, Extract

### PR DESCRIPTION
**Pull request by jmcbroome**
This PR includes a couple small requests and code related to primer dropout aberrant mutations. Specifically, the following:

1. A new option for matUtils extract that changes the behavior of random context sample selection to limit said random samples to below the LCA of all chosen samples (-Z), requested by Russ
2. A new masking routine which performs local or global masking of mutations
3. New tests included in experimental primer dropout detection routine in matUtils uncertainty
4. A bugfix/refactor to simply use collapse_tree() before polytomy resolution instead of attempting to track and remove single children in function
5. Minor formatting changes and assertions

### CODE REVIEW

**Comment by yatisht** [comment]
Is there any reason you are masking mutations that are problematic instead of just getting rid of them? We were masking (setting pos to -1) earlier for a very different objective (to hide restricted sample-specific mutations).

**Comment by jmcbroome** [comment]
I wanted to write this function in such a way that optimization can ignore these sites without altering the original tree structure, to show that ignoring these mutations specifically can lead to an outsize improvement in overall tree parsimony/placement (and therefore that their presence is a problem). If we deleted it outright, the original pre-optimization structure of both trees is different, which is confounding to some degree. 

In a more general sense, this could also be used when investigating whether the presence or absence of specific mutations on a part of a tree affects placement, again without altering tree structure. In any case, this is under "mask", so I was inclined to mask it. Would you be satisfied if I add another "delete" flag or similar which instead deletes all otherwise-masked mutations? Such a flag may cause some segfault issues but I can try to implement something.

**Comment by yatisht** [comment]
The optimizer needs to know the state of each node at each site (ambiguous bases are allowed now), so when you say the "optimization can ignore these sites without altering the original tree structure", do you mean that the optimizer should treat the site as ambiguous (equivalent to 'N') or parsimony-resolve it based on the parent state? Currently, it's the latter, and you will get the same result if you just delete that mutation.

**Comment by jmcbroome** [comment]
Ah, I'd misunderstood exactly how Cheng chose to handle it when he said it ignores it. I was thinking it should be treated as ambiguous so that the optimization with and without taking that specific mutation's identity into account is best controlled. I'll agree that its essentially splitting hairs either way, though. 

I'll reiterate my previous question- do you think I should add a flag to delete instead of mask the requested mutation? If I were to outright delete them always, I'm not sure this is the right place for such a function, but I don't know where a "delete this suite of mutations" function would go in the rest of the package.

**Comment by jmcbroome** [comment]
Additionally, I just added a quick tweak to the tree rotation function to optionally reverse the sort for display (so that it doesn't overlap with Auspice key output with JSON), and add it to the JSON generation routine, as requested by Russ. It defaults to current sorting behavior so should not affect other parts of the codebase.

**Pull request merged**
