### PR TITLE
Support Diff file from MAPLE

### PR DESCRIPTION
**Pull request by yceh**
Diff file from MAPLE can now be used with reference FASTA and a Newick tree input.
Fix extra N in matUtils extract.

### CODE REVIEW

**Comment by yatisht** [comment]
This is really cool. FYI, @NicolaDM.

**Comment by russcd** [comment]
@AngieHinrichs and @lilymaryam may also want to take a look at this.

**Comment by yceh** [comment]
By the way, transposed VCF ( https://github.com/yatisht/usher/blob/master/src/matOptimize/transpose_vcf/transposed_vcf.md ) is better supported than the Diff file. It is essentially a block gzipped binary version of the diff file to be loaded in parallel easily.

**Comment by NicolaDM** [comment]
That's really great, these seem to me like amazing features!

**Pull request merged**
