### PR TITLE
Better loging and documentation

### PR DESCRIPTION
**Pull request by yceh**
This is mostly fixing compiler warning and cleaning up the code.
The large radius bug has been fixed, I forgot the pass the argument last time. However, radius cannot be too large, as I am using recursion, but a radius of 100 shouldn't be a problem.
Merging with mainline will be difficult, as I represent Mutation class differently, so I am currently adding placement code.

### CODE REVIEW

**Comment by yatisht** [comment]
@yceh  I ran this and I have a few minor comments:

1. If I just type `./tree_rearrange_new`, it should print a help message instead of `ERROR: Could not open the tree file: !`.
2. It initially prints `assigned XXX`, which is not very insightful. Besides, those numbers appear to be random, e.g. 3589 appeared before 1382. Could you please make it more sensible?
3. I think you should use escape character '\r' at the beginning of print statement instead of at the end (e.g. "\rassigned %d" instead of "assigned %d\r") because the cursor appears to be dancing currently
4. Do you think you could add an option `--save-every` to save a MAT (original format) every specified number of seconds, similar to matOptimize?
5. I am still a bit worried about you using your own `mutation_annotated_tree` structure. There is code replication currently, which will make it hard to maintain.

**Comment by yatisht** [comment]
You are also saving a number of intermediate files 0.pb, 1.pb etc. They are pretty large. Do you really need to store them?

**Comment by yceh** [comment]
1. I will fix it when argc==1.
2. It is the last position whose state have been assigned. Because I split the VCF into chunks and parse each chunk in parallel, it is possible for some latter positions to get parsed and done with Fitch sankoff earlier than earlier position. Some idea on how to make the display more sensible will be very helpful :)
3. Thanks! This might be the reason why it doesn't erase the entire line as well.
4. It is difficult, because I need to terminate the search to apply moves, also searching a single src will take a minute or 2 on trees like 05-28. However, you can press Ctrl-C to stop a search and apply the moves found so far.
5. I agree, but I need the Mutation_Collection class and the Valid_Mutation class (for placement later). I try to merge it into mainline, but it leads to a lot of confusing ifdef to multiplex mutation_annotated_tree.hpp. Therefore, I am working on the placement, and after I finish, I will port all functionality of usher into it.

As for the intermediate files, they are written once and never read. They are just for continuing optimization quickly with -a argument if the process is killed in the middle.

**Comment by yatisht** [comment]
1. Actually, I wanted a help message for any unexpected command line argument(s). We do that in usher currently, if you want to borrow the code.
2. I had the same issue with matOptimize. Instead of printing the last updated site, you can print how many sites have been assigned. See https://github.com/yatisht/usher/blob/master/src/matOptimize/main.cpp#L669-L677.
3. OK
4. Not sure if saving on CTRL+C is a good idea. Sometimes, the user may type an incorrect command, such as the same input and output filename, and is pressing CTRL+C to prevent overwriting the file. It can also get frustrating to wait for the file writing to complete before the program is finally killed.
5. Ok, you may have to ensure that both usher and matUtils stay compatible with your new class. That might be a lot of work but if you think it's faster than modifying the existing class, go ahead.

I would suggest not creating intermediate files unless user specifies an output directory for it.

**Comment by yceh** [comment]
1. I put output as require argument, and check each input option individually. I also output a summary of all the options the user entered after parsing.
2.  Fixed.
4. I added an option to start applying moves after a certain number of moves are found (default 1000, maybe too low). It is also possible to make the program wrap up by sending USRSIG2. (I had difficulties capturing SIGQUT, so I used SIGUSR2 instead.) The program will print its pid after argument parsing.

It now only output one intermediate file, and user have option -n to disable that.

**Comment by yatisht** [comment]
Excellent. Thanks for all the changes.

**Pull request merged**
