### PR TITLE
new_mask_function

### PR DESCRIPTION
**Pull request by lilymaryam**
Added -D and -f to matUtils mask for post-placement local masking. To be further detailed in MTB manuscript.

### CODE REVIEW

**Comment by yatisht** [comment]
@lilymaryam The build is failing (https://github.com/yatisht/usher/actions/runs/11690922774/job/33063972836?pr=383#step:3:3210). Could you please review?

**Comment by lilymaryam** [comment]
Hi Yatish, I am trying to figure this out now. Sorry about that. I'll update soon.

**Comment by lilymaryam** [comment]
Hi Yatish! I didn't realize that repo changes would be immediately reflected in my current pull request. I closed this one and opened a new one which is identical to this one. I can reopen this one if you prefer but the new one should also build without error.

**Comment by yatisht** [comment]
I merged the other one.

**Comment by lilymaryam** [comment]
Thank you!

**Pull request closed without merging**
