### PR TITLE
Radius 1 tree rearrangement

### PR DESCRIPTION
**Pull request by yceh**
This will try to search whether moving a node to its parent of parent or sibling will reduce parsimony score. If the move is profitable, it will search in its new neighborhood.
Only nodes that known to be impossible to cause conflict (aka. nodes that are not parent of each other and do not share parent) are searched in parallel.
This will be superseded by https://github.com/yceh/usher/tree/tree_moves/src/tree_rearrangements, which is can search in variable radius can search all nodes in parallel, if I can finish that in time.

### CODE REVIEW

**Comment by yatisht** [comment]
Have you tested this on some examples? Could you add those examples to https://github.com/TurakhiaLab/usher_tests?

**Comment by yceh** [comment]
I couldn't really use matToVCF to check whether the tree movements have accidentally changed the mutation each sample carries or whether t drops some samples, as it reorders the sample columns from DFS result, which changes after the tree moves. 
This is checked in src/check_samples.cpp.
On the pruning experiment in the test repo, it modestly reduces parsimony score from 36021 to 35956.

**Comment by yceh** [comment]
Command line argument --refine-tree turns on tree moves.

**Comment by yatisht** [comment]
An improvement from 36021 to 35956 for radius=1 is quite impressive. I'll try this out and review your code in detail in a day or so.

**Comment by AngieHinrichs** [comment]
> I couldn't really use matToVCF to check whether the tree movements have accidentally changed the mutation each sample carries or whether t drops some samples, as it reorders the sample columns from DFS result, which changes after the tree moves.

In case it helps, I'm attaching a script (vcfNormalizeGt.pl; I had to rename it to vcfNormalizeGt.pl.txt in order to get github to accept it) that I wrote for comparing VCF files.  It removes several columns, leaving only POS, REF, ALT and the sample genotype columns.  It also reorders the sample genotype columns alphabetically by sample name, sorts the ALT column values alphabetically (e.g. "G,C" --> "C,G") and replaces the genotype column numeric values with alleles (so if ref=A and alt=G,C in the input, then 0 --> A, 1 --> G, 2 --> C).  When two VCF files are normalized in that way, you can diff the normalized versions to test whether any samples or alleles change.

[vcfNormalizeGt.pl.txt](https://github.com/yatisht/usher/files/5927875/vcfNormalizeGt.pl.txt)

**Comment by yatisht** [comment]
Wonderful, thanks @AngieHinrichs!

**Comment by yceh** [comment]
Superseded by https://github.com/yatisht/usher/pull/30

**Pull request closed without merging**
