### PR TITLE
Usher matoptimize fuse

### PR DESCRIPTION
**Pull request by yceh**
Merged usher and matOptimize. Not confident for clade assignment working correctly. 
It will adjust the optimization radius so that each round can finish in a time interval (5 min default), the radius of last round of optimization can be set separately.

### CODE REVIEW

**Comment by yceh** [comment]
I haven't implemented no-add and print-parsimony-score. ripples-mapper will work better for them.

**Comment by AngieHinrichs** [comment]
`usher --no-add --detailed-clades` is used by pangolin, and with the next release of pangolin, usher will be the default mode.  So it will be very important to make sure that the next release of usher works with pangolin.

**Comment by yceh** [comment]
--no-add and --detailed-clade is working, but because this defines valid sibling placement more stringently, requiring shared mutation. (I had some difficulties replicating old usher behavior exactly.), 10% of clade assignments will be different.
-B option will do some tie-breaking at the end to minimize back mutations.
I am following along with the daily builds to check for bugs.

**Comment by AngieHinrichs** [comment]
@yceh Can you share some example sequence names and differing clade assignments?  I would like to take a look at a few.

**Pull request merged**
